name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*.*'  # This pattern matches semantic versioning tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from Git tag
      run: echo "DOCKER_IMAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ env.DOCKER_IMAGE_VERSION }}
